[package]
name = "stock"
version = "0.0.1-alpha.1"
edition = "2021"
authors = ["dravenk <longxianwen@outlook.com>"]
license = "MIT OR Apache-2.0"
description = "Use the command line tool with query cryptocurrency prices"
readme = "README.md"
[dependencies]
reqwest = "0.11.24"